In [35]:
import numpy as np
# there are 2000 words
alpha = np.full (2000, .1)

# there are 100 topics
beta = np.full (100, .1)

# this gets us the probabilty of each word happening in each of the 100 topics
wordsInTopic = np.random.dirichlet (alpha, 100)

# produced [doc, topic, word] gives us the number of times that the given word was
# produced by the given topic in the given doc
produced = np.zeros ((50, 100, 2000))

# generate each doc
for doc in range (0, 50):
        #
        # get the topic probabilities for this doc
        topicsInDoc = np.random.dirichlet (beta)
        #
        # assign each of the 2000 words in this doc to a topic
        wordsToTopic = np.random.multinomial (2000, topicsInDoc)
        #
        # and generate each of the 2000 words
        for topic in range (0, 100):
                produced[doc, topic] = np.random.multinomial (wordsToTopic[topic], wordsInTopic[topic])

In [36]:
#1st Question
produced[18, 17, :].sum()

0.0

In [37]:
#2nd Question
produced[18, 17:46, :].sum()

1091.0

In [38]:
#3rd Question
produced.sum()

100000.0

In [39]:
#4th Question
produced[:, 17, :].sum()

512.0

In [40]:
#5th Question
produced[:, [17, 23], :].sum()

2081.0

In [41]:
produced[:, np.array([17, 23]), :].sum()
#This answer is given in the question,I was just confirming if I am getting the correct solution or not. As you can see i am getting same result

2081.0

In [42]:
#6th Question
produced[:, ::2, :].sum()

47170.0

In [43]:
produced[:,np.arange(0,100,2),:].sum ()
#This answer is given in the question,I was just confirming if I am getting the correct solution or not. As you can see i am getting same result

47170.0

In [44]:
#7th Question
produced[:, 15, :].sum(axis=0)

array([0., 0., 0., ..., 0., 0., 0.])

In [45]:
#8th Question
produced.sum(axis=0).argmax(axis=0)

array([74,  1, 74, ..., 19, 11, 23])

In [46]:
#9th Question
produced.sum(axis=0).max(axis=1)

array([11., 36., 24., 12., 25., 26., 34., 10., 19., 39., 15., 25., 21.,
       16., 10., 21., 16., 14., 23., 30., 18., 11., 36., 35., 14., 61.,
       32., 30., 45., 18., 32., 46., 39., 88., 17., 15.,  8., 14., 22.,
       25., 17., 10.,  8., 48., 19.,  9., 21., 45., 18., 23., 27., 10.,
       15., 21., 11., 34., 29., 30., 24., 30., 14., 17., 20., 10., 24.,
       12., 31., 41., 21., 31., 20., 12., 24., 29., 54., 30., 22., 69.,
       29., 23., 21., 16., 21., 15., 60., 31., 48., 26., 30., 14., 24.,
       27., 24., 26., 27., 23., 18., 50., 18., 38.])

In [47]:
produced[:,np.arange(0,100,1),produced.sum (0).argmax
(1)].sum(0)
#This answer is given in the question,I was just confirming if I am getting the correct solution or not. As you can see i am getting same result

array([11., 36., 24., 12., 25., 26., 34., 10., 19., 39., 15., 25., 21.,
       16., 10., 21., 16., 14., 23., 30., 18., 11., 36., 35., 14., 61.,
       32., 30., 45., 18., 32., 46., 39., 88., 17., 15.,  8., 14., 22.,
       25., 17., 10.,  8., 48., 19.,  9., 21., 45., 18., 23., 27., 10.,
       15., 21., 11., 34., 29., 30., 24., 30., 14., 17., 20., 10., 24.,
       12., 31., 41., 21., 31., 20., 12., 24., 29., 54., 30., 22., 69.,
       29., 23., 21., 16., 21., 15., 60., 31., 48., 26., 30., 14., 24.,
       27., 24., 26., 27., 23., 18., 50., 18., 38.])